### ISSUE TITLE
你能支持 DeepSeekMoE 模型吗？

### ISSUE THREAD

**Issue by win10ogod** [metame-none/lit-gpt-chinese#1]
你能支持 DeepSeekMoE 模型的微调和预训练吗？
另外ChatGLM3的前身似乎具有双向注意力，但在您的实现中并没有看见，我想训练一个具有双向注意力的模型，您能实现吗?

**Comment by metame-none** [comment]
目前暂时没有计划支持DeepSeekMoE
ChatGLM3我是按照官方Huggingface的实现复现的，可以实现相同输入，输出结果完全一致，如果有其它需要，需要您自己修改了。lit-gpt的优点就是代码结构相对简单，方便学习修改。
